# Generated by Django 5.1.7 on 2025-03-17 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerskill',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_skills', to='user.developer'),
        ),
        migrations.AddField(
            model_name='developerskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_skills', to='skills.skill'),
        ),
        migrations.AlterUniqueTogether(
            name='developerskill',
            unique_together={('developer', 'skill')},
        ),
    ]
